import { ContestantCombined } from "../app/contestantCombined";

export const CONTESTANTS: ContestantCombined[] = [
  // tslint:disable-next-line: max-line-length
  {
    id: 1,
    points: 11,
    distance: 11,
    firstName: "aaa",
    lastName: "aaa",
    avatar: "boss",
    gender: "m",
    userName: "aaa",
    userId: 1,
    rank: 1,
    activityId: 1,
    challengeId: 1,
    activityName: "combined",
    userChart: "aaa",
    leaderboardPieChartData: null
  },
  {
    id: 2,
    points: 22,
    distance: 22,
    firstName: "bbb",
    lastName: "bbb",
    avatar: "boss",
    gender: "m",
    userName: "bbb",
    userId: 1,
    rank: 2,
    activityId: 1,
    challengeId: 1,
    activityName: "combined",
    userChart: "bbb",
    leaderboardPieChartData: null
  },
  {
    id: 3,
    points: 33,
    distance: 33,
    firstName: "ccc",
    lastName: "ccc",
    avatar: "boss",
    gender: "m",
    userName: "ccc",
    userId: 1,
    rank: 3,
    activityId: 1,
    challengeId: 1,
    activityName: "combined",
    userChart: "ccc",
    leaderboardPieChartData: null
  },
  {
    id: 4,
    points: 44,
    distance: 44,
    firstName: "ddd",
    lastName: "ddd",
    avatar: "boss",
    gender: "m",
    userName: "ddd",
    userId: 1,
    rank: 4,
    activityId: 1,
    challengeId: 1,
    activityName: "combined",
    userChart: "ddd",
    leaderboardPieChartData: null
  },
  {
    id: 5,
    points: 55,
    distance: 55,
    firstName: "eee",
    lastName: "eee",
    avatar: "boss",
    gender: "m",
    userName: "eee",
    userId: 1,
    rank: 5,
    activityId: 1,
    challengeId: 1,
    activityName: "combined",
    userChart: "eee",
    leaderboardPieChartData: null
  },
  {
    id: 6,
    points: 66,
    distance: 66,
    firstName: "fff",
    lastName: "fff",
    avatar: "boss",
    gender: "m",
    userName: "fff",
    userId: 1,
    rank: 6,
    activityId: 1,
    challengeId: 1,
    activityName: "combined",
    userChart: "fff",
    leaderboardPieChartData: null
  }
];
